apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-crm-ingress
spec:
  rules:
    - host: osher-demo.ddns.net
      http:
        paths:
          - backend:
              service:
                name: demo-crm-service
                port:
                  number: 80
            path: /
            pathType: Prefix
