controller:
  image:
    repository: ingress-controller/controller
    tag: 1.0.0-dev
    digest: null

  service:
    type: LoadBalancer
    annotations:
      cloud.google.com/load-balancer-type: 'Internal'
